name: test-dplyr

on: [push, pull_request]


jobs:
  test-find_release:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: install tagbot
        run: |
          install.packages("remotes")
          remotes::install_local()
        shell: Rscript {0}
      - uses: actions/checkout@v2
        with:
          repository: tidyverse/dplyr
          fetch-depth: 0
      - name: remove last tag
        run: |
          release <- tagbot::find_release()
          cliff::run("git", "checkout", "-b", "last-tag-branch", release$tag)
          cliff::run("git", "checkout", "main")
          cliff::run("git", "tag", "-d", release$tag)
        shell: Rscript {0}
      - name: find release
        run: |
          tagbot::find_release()
        shell: Rscript {0}

  test-changelog:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: install tagbot
        run: |
          install.packages("remotes")
          remotes::install_local()
        shell: Rscript {0}
      - uses: actions/checkout@v2
        with:
          repository: tidyverse/dplyr
          fetch-depth: 0
      - name: print changelog
        run: |
          tagbot::changelog()
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
